start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[mode.main.binding]
alt-enter = 'exec-and-forget open -n -a wezterm'
alt-shift-c = 'reload-config'
alt-r = 'mode resize'
alt-shift-space = 'layout floating tiling'
alt-shift-f = 'fullscreen'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move-through left'
alt-shift-j = 'move-through down'
alt-shift-k = 'move-through up'
alt-shift-l = 'move-through right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace code'
alt-2 = 'workspace www'
alt-3 = 'workspace term'
alt-4 = 'workspace notes'
alt-5 = 'workspace chat'
alt-6 = 'workspace music'
alt-7 = 'workspace study'

alt-shift-1 = 'move-node-to-workspace code'
alt-shift-2 = 'move-node-to-workspace www'
alt-shift-3 = 'move-node-to-workspace term'
alt-shift-4 = 'move-node-to-workspace notes'
alt-shift-5 = 'move-node-to-workspace chat'
alt-shift-6 = 'move-node-to-workspace music'
alt-shift-7 = 'move-node-to-workspace study'

[mode.resize.binding]
h = 'resize width +50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width -50'
esc = 'mode main'
