font_family JetBrainsMono NF Regular
font_size 13.0

# Trust me, ligatures are bad.
disable_ligatures always

map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down

map f1 launch --cwd=current

cursor_shape underline

# BEGIN_KITTY_THEME
# Tokyo Night Storm
include current-theme.conf
# END_KITTY_THEME

enable_audio_bell no
