# Fonts
font_family family="Terminess Nerd Font Mono"
font_size 12.0

# Disable italics as Terminess Italic just looks weird.
italic_font family="Terminess Nerd Font Mono" style="Regular"
bold_italic_font family="Terminess Nerd Font Mono" style="Bold"

# Trust me, ligatures are bad.
# I was debugging a bug just because someone did not use tripe equality in javascript and I did not see that...
disable_ligatures always

# Mappings
map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down
map ctrl+shift+n new_os_window_with_cwd

# unmap these two as i need them in nvim for buffer resize
map ctrl+shift+h
map ctrl+shift+l

# Theme and Customization
cursor_shape underline
window_padding_width 5

# Tabs
tab_bar_style powerline
tab_bar_edge bottom
tab_bar_align left
tab_bar_min_tabs 1
tab_title_template "{index}: {title}"

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME

# Misc
enable_audio_bell no
macos_quit_when_last_window_closed yes

