exec-once = swaybg -i ~/Pictures/Wallpapers/gray-wavy-lines.jpg & lxpolkit
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Storm-B'
monitor=eDP-1,disable
monitor=DP-2,2560x1440@144,0x0,1
monitor=DP-1,2560x1440@144,2560x0,1

input {
    kb_options = ctrl:nocaps
    kb_options = grp:caps_toggle
    kb_layout = us,de
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    layout = dwindle
}

gestures {
    workspace_swipe = true
    workspace_swipe_invert = false
    workspace_swipe_forever = true
}

decoration {
    rounding = 0
    drop_shadow = true
    shadow_range = 6
    shadow_render_power = 5
    shadow_ignore_window = true
    col.shadow = rgba(1a1a1aee)
    dim_inactive = false
    dim_strength = 0.1
}


animations {
    enabled=1
    bezier=overshot,0.13,0.99,0.29,1.1
    animation=windows,1,4,overshot,slide
    animation=border,1,10,default
    animation=fade,1,10,default
}

misc {
    disable_hyprland_logo = true
}

$mainMod = SUPER
$mainModWithShift = SUPER_SHIFT
$mainModWithAlt = SUPER_ALT

# Window keybinds
bind = $mainMod, Return, exec, kitty
bind = $mainMod, Q, killactive,
bind = $mainModWithShift, Q, exit, 
bind = $mainMod, E, exec, GTK_THEME='Tokyonight-Storm-B' nautilus
bind = $mainMod, F, exec, firefox
bind = $mainModWithShift, Space, togglefloating, 
bind = $mainMod, D, exec, wofi --show drun
bind = $mainMod, P, exec, ~/.config/rofi/powermenu.sh
bind = $mainMod, M, fullscreen, 1

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Multimedia keybinds
bind = , 122, exec, pactl set-sink-volume @DEFAULT_SINK@ -2%
bind = , 123, exec, pactl set-sink-volume @DEFAULT_SINK@ +2%
bind = , 121, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , 173, exec, playerctl previous
bind = , 171, exec, playerctl next
bind = , 172, exec, playerctl play-pause
bind = , 232, exec, brightnessctl set 10%-
bind = , 233, exec, brightnessctl set 10%+

# Script keybinds
bind = $mainModWithAlt, L, exec, swaylock-fancy
bind = $mainMod, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainModWithShift, S, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/screenshot-$(date +'%Y%m%d-%H%M%S').png
bind = $mainMod, B, exec, ~/.local/bin/toggle-bar.sh
bind = $mainModWithShift, N, exec, ~/.local/bin/night-mode.sh
bind = $mainModWithShift, U, exec, ~/.local/bin/log-time.sh

# Monitor keybinds
bind = $mainModWithShift, O, exec, hyprctl keyword monitor eDP-1,disable
bind = $mainModWithShift, I, exec, hyprctl keyword monitor eDP-1,1920x1080,0x0,1


# Resizing windows submap
bind=ALT,R,submap,resize
submap=resize
binde=,l,resizeactive,40 0
binde=,h,resizeactive,-40 0
binde=,k,resizeactive,0 -40
binde=,j,resizeactive,0 40
bind=,escape,submap,reset 
submap=reset

bind=$mainModWithShift,h,movewindow,l
bind=$mainModWithShift,l,movewindow,r
bind=$mainModWithShift,j,movewindow,d
bind=$mainModWithShift,k,movewindow,u
