{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    rustup
    gnumake
    vim
    htop
    killall
    wget
    firefox
    neovim
    kitty
    wl-clipboard
    loupe
    wofi
    pavucontrol
    python3
    wezterm
    spotify
    gcc13
    mpv
    gnome.nautilus
    gnome.gnome-disk-utility
    waybar
    webcord
    xwayland
    lazygit
    nodePackages_latest.typescript-language-server
    nodePackages_latest.bash-language-server
    nodePackages_latest.pyright
    python311Packages.jedi-language-server
    tailwindcss-language-server
    prettierd
    ripgrep
    vscode-langservers-extracted
    iwgtk
    file
    grim
    slurp
    tokyo-night-gtk
    libnotify
    gammastep
    playerctl
    libimobiledevice
    ifuse
    # todo: move to home-manager
    fishPlugins.z
    chromium
    swaybg
    util-linux
    waypaper
    jq
    lua-language-server
    stylua
    obsidian
    nodejs_22
    corepack_22
    pkg-config
    openssl
    android-tools
    vulkan-tools
    rbw
    rofi-rbw-wayland
    pinentry
    wtype
    php83Packages.composer
    nh
    hyprlock
    protonmail-bridge-gui
    thunderbird
    statix
    swaynotificationcenter
    kooha
    openjdk17-bootstrap
    rclone
    postgresql_16
    # needed for react native building, android-nixpkgs should provide these but they are currently broken ):
    aapt
    cmake
    # end
    act
    solaar
    wlogout
  ];
}
