{ pkgs, ... } :

{
  environment.systemPackages = with pkgs; [
     rustup
     gnumake
     vim
     htop
     killall
     wget
     firefox
     neovim
     kitty
     wl-clipboard
     loupe
     wofi
     pavucontrol
     python3
     wezterm
     spotify
     gcc13
     mpv
     gnome.nautilus
     waybar
     webcord
     xwayland
     lazygit
     nodePackages_latest.typescript-language-server
     nodePackages_latest.bash-language-server
     nodePackages_latest.pyright
     python311Packages.jedi-language-server
     tailwindcss-language-server
     prettierd
     ripgrep
     vscode-langservers-extracted
     iwgtk
     file
     grim
     slurp
     tokyo-night-gtk
     libnotify
     gammastep
     playerctl
     libimobiledevice
     ifuse
     # todo: move to home-manager
     fishPlugins.z
     chromium
     polkit
     polkit-kde-agent
     swaybg
     util-linux
     waypaper
     jq
     lua-language-server
     stylua
     obsidian
     nodejs_18
     corepack
     pkg-config
     openssl
     android-tools
     vulkan-tools
     rbw
     rofi-rbw-wayland
     pinentry
     wtype
     php83Packages.composer
     nh
     hyprlock
     protonmail-bridge
     thunderbird
     gnome.gnome-keyring
     statix
     swaynotificationcenter
     kooha
  ];
}
